#|
library(readxl)
library(openxlsx)
library(here)
library(dplyr)
library(tidyr)
library(ggplot2)
library(arrow)
library(data.table)
library(tictoc)
library(knitr)
library(kableExtra)
library(DT)
library(sf)
library(httr)
library(jsonlite)
require(icesConnect)
library(officer)
library(flextable)
library(ggalluvial)


here::i_am("project.Rproj")
