---
title: "Data reading"
subtittle: "subtitle" 
date: "`r format(Sys.Date(), '%d %B %Y')`"
author: Laurent Dubroca 
bibliography: /Users/moi/zotero/exportdb/MyLibrary.bib 
number-sections: true
toc: true
toc-depth: 3
toc-expand: 3
format:
  html:
    html-math-method: katex
    css: styles.css
    code-fold: true
execute:
    warning: false
---

# Framework 

Analyses and results in a reproducible format (code and output) following
reproducible framework [@powers2019].

Data read and co.


```{r renderstuff,eval=F,include=F}
#| cache: true
#| echo: false
#|
quarto::quarto_render("report_data_read.qmd")
```


```{r libraryandco,eval=T,include=T}
#|
library(readxl)
library(openxlsx)
library(here)
library(dplyr)
library(ggplot2)
library(arrow)
library(data.table)
library(tictoc)
library(knitr)
library(kableExtra)
library(DT)
library(sf)
library(httr)
library(jsonlite)
require(icesConnect)


here::i_am("project.Rproj")
```

# Parameters

```{r dataco,eval=T,include=T}
#|
#source keyring (token stuff)
keyringfile<-here("analyses","keyring.R")
if(file.exists(keyringfile)){
	source(keyringfile)
}else{
	stop("keyring file not found")
}	
#keyring file is a short R code used to tokenize data exchange
#go to https://data.ices.dk/token to generate the token
#the sourced code is :
#require(icesConnect)
#icesConnect::set_username("john.doe")
#icesConnect:::token_set_from_keyring(
#"thelongcaracterchainofthetokenprovidedbyiceshastobypastedhere",
#    username = "john.doe"
#)
 
# read the data from ices API
linkD1<-"https://bycatch.ices.dk/api/GetD1_Fishing_effort"
linkD2<-"https://bycatch.ices.dk/api/GetD2_Bycatch_monitoring_effort"
linkD3<-"https://bycatch.ices.dk/api/GetD3_BycatchEvent"
# data request

if(file.exists(here("data","D1_wgbyc.csv"))){
    #read dowloaded data
    D1<-fread(here("data","D1_wgbyc.csv"))
    D2<-fread(here("data","D2_wgbyc.csv"))
    D3<-fread(here("data","D3_wgbyc.csv"))
}else{
    options(icesSAG.use_token=T)
    resp1<-ices_get_jwt(linkD1)
    D1<-content(resp1,as="text")
    D1<-fromJSON(D1)
    resp2<-ices_get_jwt(linkD2)
    D2<-content(resp2,as="text")
    D2<-fromJSON(D2)
    #D3 request by year: API slow by construction
    D3<-data.frame()
    for(idyear in 2017:2025){
            print(idyear)
            resp3<-ices_get_jwt(paste0(linkD3,"?year=",idyear))
            D3tmp<-content(resp3,as="text")
            D3tmp<-fromJSON(D3tmp)
            D3<-rbind(D3,D3tmp)
    }
    #save file in csv format into data dir
    write.csv(D1,file=here("data","D1_wgbyc.csv"),row.names=F)
    write.csv(D2,file=here("data","D2_wgbyc.csv"),row.names=F)
    write.csv(D3,file=here("data","D3_wgbyc.csv"),row.names=F)
}

#get extra info to label stuff
if (F) {
    #read dowloaded data
    listvocab<-c("IC_Country","GearType","GearGroup")
    f1<-function(vocabname){
        tmp<-fread(here("data","vocab",paste0(vocabname,".csv")))
        assign(vocabname,tmp,".GlobalEnv")
    }
    lapply(listvocab,f1)
}else{
    #downloaded locally some ICES vocab
    listvocab<-c("IC_Country","GearType","GearGroup")
    f1<-function(vocabname){
        pipo <- icesVocab::getCodeList(vocabname)
        write.csv(pipo, file = here("data/vocab",paste0(vocabname,".csv")),row.names=F)
    }
    lapply(listvocab,f1)
}



```


# Exploratory data analysis 

```{r explo1,cache=TRUE,eval=T,echo=T,cache=F,include=T}

summary1<-D1%>%
    group_by(year,ecoregion)%>%
    summarise(eff=sum(daaysAtSeaF,na.rm=T))



```

# R session information

```{r Rsession,cache=TRUE,eval=T,echo=T,cache=F,include=T}
sessioninfo::session_info()
```

# Bilbiography
